# Generated by Django 4.2.3 on 2023-08-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='facbook_id',
            new_name='facebook_id',
        ),
    ]
